# Family Profile
# google:
#   credentials_path: "./secrets/google-credentials.json"
#   spreadsheet_name: "2025 CC Transactions"
#   worksheet_name: "October2"

# Real Estate Profile
google:
  credentials_path: "./secrets/google-credentials.json"
  spreadsheet_name: "2025 Real Estate"
  worksheet_name: "2024-all"
